# Generated by Django 5.0 on 2023-12-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_category_author_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
